name: "fasttodo-dev"
services:
  db:
    image: postgres:17.5
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fasttodo-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "FastTodo"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: catsarecool
    ports:
      - 5050:80
    networks:
      - fasttodo-network

  redis:
    image: redis:7.4.0-alpine
    environment:
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    ports:
      - 6379:6379
    networks:
      - fasttodo-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ['redis-server']

  migrator:
    container_name: fasttodo-migrator
    build:
      context: ../
      dockerfile: Dockerfile.Migrations
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - DB_PROJECT=${DB_PROJECT}
      - CONTEXT=${CONTEXT}
      - IDENTITY_CONNECTION_STRING=${IDENTITY_CONNECTION_STRING}
      - IDENTITY_PROJECT=${IDENTITY_PROJECT}
      - IDENTITY_CONTEXT=${IDENTITY_CONTEXT}
      - fastTodoOption__SQLProvider=${SQLProvider}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fasttodo-network
    restart: "no"

volumes:
  pgdata:

networks:
  fasttodo-network:
